debug: true

management:
  security:
    enabled: false

ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000
  eureka:
    enabled: true


#单个访问请求持续时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#            feign client 在启用hystrix的情况下，会在hystrix 启动的子线程中发送请求，造成子线程中获取不到securitycontext，从而导致认证失败，改变线程隔离策略为SEMAPHORE，就可以正常传递了
          strategy: SEMAPHORE
#  shareSecurityContext: true

server:
  port: 9000



spring:
  application:
    name: resource-service-jwt
  rabbitmq:
    host: localhost
#  zipkin:
#    enabled: true
#    baseUrl: http://localhost:12000/
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth2db?serverTimezone=CST
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  sleuth:
    stream:
      enabled: true
    sampler:
     # 采样率，默认0.1即10%,如需测试时每次都看到trace则修改为1.0，但对性能有影响，注意上线时修改为合理值
      percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: WARN

security:
  ignored: /noauth/**, /swagger**,/swagger**/**,/webjars/**,/v2/**, /js/**, /css/**, /hystrix.stream/**
  basic:
    enabled: false
  sessions: stateless


#feign:
#  hystrix:
#    enabled: false

