debug: true


ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000
  eureka:
    enabled: true


#单个访问请求持续时间
hystrix:
  command:
#  default 这里可以是微服务的名称。
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
          strategy: SEMAPHORE
#  shareSecurityContext: true

server:
  port: 9001



spring:
  application:
    name: resource-service-jwt-feign
  rabbitmq:
    host: localhost
  zipkin:
    enabled: true
    baseUrl: http://localhost:12000/
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth2db?serverTimezone=CST
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  sleuth:
    stream:
      enabled: true
    sampler:
     # 采样率，默认0.1即10%,如需测试时每次都看到trace则修改为1.0，但对性能有影响，注意上线时修改为合理值
      percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: WARN

security:
  basic:
    enabled: false
  sessions: stateless



#feign:
#  hystrix:
#    enabled: false
#hystrix.command.default.execution.isolation.strategy: SEMAPHORE