---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apigateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: 15.114.100.72:80/com.springcloud.template/zuul-server-with-oauth2-jwt
          imagePullPolicy: Always
          ports:
          - name: server-port
            containerPort: 14000
      imagePullSecrets:
        - name: myregistrykey
---
kind: Service
apiVersion: v1
metadata:
  name: apigateway-service
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 14000
      targetPort: 14000
      nodePort: 9527